### PR TITLE
Convert to swift 3

### PR DESCRIPTION
**Pull request by jaredchu**

### CODE REVIEW

**Review by yarodevuci — APPROVED** [review]

**Comment by yarodevuci** [comment]
It is not even working....

**Comment by jaredchu** [comment]
works like a champ with my current project

**Comment by yarodevuci** [comment]
Hm, weird. Doest it get stuck in UITransitionView that block regular view?
How to get rid bouncy up animation on the player?

**Comment by jaredchu** [comment]
Sorry for late response, I'm tested it again and it's running normally. The pod 'ARNTransitionAnimator' also needed to convert to swift3. Could you provide some screenshots about your issues, I can't image that.

**Comment by xxxAIRINxxx** [comment]
@jaredchu 
Thank you for PR.
but sorry..
It updated to a new version!
please try it 😃

**Pull request closed without merging**
